version: '3.1'
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run start
