// MAIN ACTIONS
export const SET_USER_LOGIN = "SET_USER_LOGIN";

// WEBSOCKET ACIONS TYPES
export const WEBSOCKET_OPEN = "WEBSOCKET_OPEN";
export const WEBSOCKET_CONNECT = "WEBSOCKET_CONNECT";
export const WEBSOCKET_CONNECTED = "WEBSOCKET_CONNECTED";
export const WEBSOCKET_SEND = "WEBSOCKET_SEND";
export const WEBSOCKET_MESSAGE = "WEBSOCKET_MESSAGE";
export const WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED";
export const WEBSOCKET_DISCONNECT = "WEBSOCKET_DISCONNECT";
export const WEBSOCKET_DISCONNECTED = "WEBSOCKET_DISCONNECTED";
export const WEBSOCKET_RECONNECTED = "WEBSOCKET_RECONNECTED";
export const WEBSOCKET_BROKEN = "WEBSOCKET_BROKEN";
export const WEBSOCKET_SET_AUTO_RECONNECT = "WEBSOCKET_SET_AUTO_RECONNECT";
export const WEBSOCKET_SET_STATUS = "WEBSOCKET_SET_STATUS";
export const WEBSOCKET_JOIN_ROOM = "WEBSOCKET_JOIN_ROOM";
export const WEBSOCKET_LEAVE_ROOM = "WEBSOCKET_LEAVE_ROOM";
export const WEBSOCKET_SET_ROOM_ID = "WEBSOCKET_SET_ROOM_ID";

//CREATE ROOM
export const CREATE_ROOM = "CREATE_ROOM";
export const CREATE_ROOM_FAILED = "CREATE_ROOM_FAILED";

//MONITORING
export const MONITORING_FETCH_ROOM = "MONITORING_FETCH_ROOM";
export const MONITORING_UPDATE_ROOM_STATUS = "MONITORING_UPDATE_ROOM_STATUS";
export const MONITORING_REFRESH_SCREEN = "MONITORING_REFRESH_SCREEN";
export const MONITORING_DESTROY = "MONITORING_DESTROY";
export const MONITORING_SET_STUDENT_URL = "MONITORING_SET_STUDENT_URL";
export const MONITORING_SET_ASSISTANT_URL = "MONITORING_SET_ASSISTANT_URL";

//WATCHING
export const WATCHING_SET_START = "WATCHING_SET_START";
export const WATCHING_USER_RESET = "WATCHING_USER_RESET";
export const WATCHING_SET_TYPE = "WATCHING_SET_TYPE";
export const WATCHING_SET_LOADING = "WATCHING_SET_LOADING";
export const WATCHING_SET_USER = "WATCHING_SET_USER";
export const WATCHING_SET_USER_STATUS = "WATCHING_SET_USER_STATUS";

//JOIN ROOM
export const JOIN_ROOM = "JOIN_ROOM";
export const JOIN_ROOM_SET_STATUS_JOIN = "JOIN_ROOM_SET_STATUS_JOIN";
export const JOIN_ROOM_SET_ACCOUNT_OPENID = "JOIN_ROOM_SET_ACCOUNT_OPENID";

//STUDENT ROOM
export const STUDENT_FETCH_ROOM = "STUDENT_FETCH_ROOM";
export const STUDENT_UPDATE_ROOM_STATUS = "STUDENT_UPDATE_ROOM_STATUS";
export const STUDENT_SET_STATUS_WATCHING = "STUDENT_SET_STATUS_WATCHING";
export const STUDENT_SET_WATCHING_USER = "STUDENT_SET_WATCHING_USER";
export const STUDENT_SET_AUDIO = "STUDENT_SET_AUDIO";
export const STUDENT_SET_MUTE = "STUDENT_SET_MUTE";
export const STUDENT_SET_SHARE_SCREEN = "STUDENT_SET_SHARE_SCREEN";
export const STUDENT_SET_ISWATCHING = "STUDENT_SET_ISWATCHING";
export const STUDENT_ROOM_TIME_OUT = "STUDENT_ROOM_TIME_OUT";
export const STUDENT_SET_SS_STOPPED = "STUDENT_SET_SS_STOPPED";
export const STUDENT_SET_STUDENT_ID_LIST = "STUDENT_SET_STUDENT_ID_LIST";

//ASSISTANT
export const ASSISTANT_JOIN_ROOM = "ASSISTANT_JOIN_ROOM";
export const ASSISTANT_JOIN_ROOM_SET_STATUS_JOIN =
  "ASSISTANT_JOIN_ROOM_SET_STATUS_JOIN";

//LOG
export const LOG_CREATE = "LOG_CREATE";
export const FETCH_LOG = "FETCH_LOG";
